title: "Hari Gunda | Researcher"
description: "Empathy-driven research for a more sustainable and peaceful world. Boren & Gilman Scholar at the University of Alabama."
url: "https://hariaksha.com"
permalink: pretty

exclude:
  - README.md
